version: "3.9"
services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379/0
      REDIS_PASSWORD: ""
      REDIS_DB_INDEX: 0
      REDIS_PERSISTENCE_ENABLED: "true"
      JWT_SECRET: dev-secret
      PROVIDER_A_API_KEY: ""
      DEFAULT_CACHE_TTL: 3600
    depends_on:
      - redis
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  redis_data:


